[package]
name = "numeric-bench-util"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[target.'cfg(unix)'.dependencies]
pprof = { version = "0.13", features = ["flamegraph", "criterion"] }
