lints.workspace = true

[package]
name = "numeric-bench-util"
version = "0.1.0"
edition = "2021"
publish = false

[features]
alloc-measures = []

[dependencies]
criterion.workspace = true
thread_local = "1.0"
atomic_cell = "0.2"

[target.'cfg(unix)'.dependencies]
#pprof = { version = "0.15", features = ["flamegraph", "criterion"] }
