[package]
name = "numeric-reals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
numeric-traits = { path = "../numeric-traits" }
numeric-utils = { path = "../numeric-utils" }
